export interface CheckOrders {
    id?:string;
    checkType?:string;
    formType?:string;    
    accountNumber:string;
    brstn:string;
    branchCode?:string;
    quantity?:string;
    deliverTo?:string;
    concode?:string;
    startingSeries?:string;
    endingSeries?:string;
    mainAccountName?:string;
    accountName1?:string;
    accountName2?:string;
    isOnHold:boolean;
    isValid:boolean;
    barcodeValue?:string;
    errorMessage?:string;
}