services:
  captive-fe:
    container_name: captive-fe
    build: .
    image: captive-fe:v1
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge